ARG ELASTICSEARCH_VERSION
FROM elasticsearch:$ELASTICSEARCH_VERSION
ARG ELASTICSEARCH_VERSION
ARG LTR_PLUGIN_VERSION=1.1.1
RUN ./bin/elasticsearch-plugin install -b http://es-learn-to-rank.labs.o19s.com/ltr-${LTR_PLUGIN_VERSION}-es${ELASTICSEARCH_VERSION}.zip
